env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  max-len: 'off'
  no-unused-vars: 'off'
  no-invalid-this: 'off'
  require-jsdoc: 'off'
  #   - error
  #   - require:
  #       FunctionDeclaration: true
  #       MethodDefinition: true
  #       ClassDeclaration: true
  #       ArrowFunctionExpression: true
  #       FunctionExpression: true
  valid-jsdoc:
    - error
    - requireReturn: false
      requireParamType: false
      requireReturnType: false
  lines-between-class-members:
    - error
    - always
